import java.util.Scanner;
import java.text.DecimalFormat;

/**
 * Will compute the value generated by a specified expression.
 *
 * @author COMP1210
 * @version 9/14/2016
 */
public class ExpressionEvaluator {
   /**
    * Main Method.
    * @param args (not used)
    */
   public static void main(String[] args) {
      Scanner userInput = new Scanner(System.in);
      double x;
      double result;
       
      System.out.print("Enter a value for x: ");
      x = Double.parseDouble(userInput.nextLine());
      
      // Equation
      result = Math.sqrt(
               Math.pow((5 * Math.pow(x, 7)) - (4 * Math.pow(x, 6)), 2)
               +
               Math.sqrt(Math.abs(3 * Math.pow(x, 5)))
               );
               
      System.out.println("Result: " + result);
      
      // Double result --> String Result
      String strResult = Double.toString(result);
      
      // Location of decimal in String Result
      int decimalAt = strResult.indexOf('.');
      
      // Index of decimal is also the number of digits to the left
      System.out.println("# digits to left of decimal point: " + decimalAt);
      
      // Length of string - 1 - decimal index equals digits to right of decimal
      System.out.println("# digits to right of decimal point: "
                         + (strResult.length() - 1 - decimalAt));
     
     // Formats Number into written format. (ex. 1,000,000.0)
      DecimalFormat fmt = new DecimalFormat("#,##0.0###");
      System.out.println("Formatted Result: " + fmt.format(result));
   }
}